
minetest.register_biome({
            name = "Biome No. 1",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -139,
            heat_point = 9.000000,
            humidity_point = 57.000000,
            scale = 10,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 2",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -109,
            heat_point = 21.000000,
            humidity_point = 7.000000,
            scale = 6,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 3",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -90,
            heat_point = 99.000000,
            humidity_point = 35.000000,
            scale = 9,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 4",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 59,
            heat_point = 51.000000,
            humidity_point = 6.000000,
            scale = 8,
            offset = 10,
    })
minetest.register_biome({
            name = "Biome No. 5",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -136,
            heat_point = 82.000000,
            humidity_point = 40.000000,
            scale = 0,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 6",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -68,
            heat_point = 8.000000,
            humidity_point = 51.000000,
            scale = 3,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 7",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 60,
            heat_point = 65.000000,
            humidity_point = 44.000000,
            scale = 3,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 8",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 150,
            heat_point = 77.000000,
            humidity_point = 39.000000,
            scale = 9,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 9",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -171,
            heat_point = 70.000000,
            humidity_point = 32.000000,
            scale = 1,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 10",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 62,
            heat_point = 56.000000,
            humidity_point = 14.000000,
            scale = 6,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 11",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 10,
            heat_point = 14.000000,
            humidity_point = 50.000000,
            scale = 5,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 12",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -29,
            heat_point = 34.000000,
            humidity_point = 17.000000,
            scale = 3,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 13",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 140,
            heat_point = 37.000000,
            humidity_point = 46.000000,
            scale = 8,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 14",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 104,
            heat_point = 72.000000,
            humidity_point = 83.000000,
            scale = 0,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 15",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -26,
            heat_point = 19.000000,
            humidity_point = 21.000000,
            scale = 3,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 16",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -193,
            heat_point = 90.000000,
            humidity_point = 91.000000,
            scale = 2,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 17",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 54,
            heat_point = 80.000000,
            humidity_point = 49.000000,
            scale = 0,
            offset = 10,
    })
minetest.register_biome({
            name = "Biome No. 18",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -154,
            heat_point = 42.000000,
            humidity_point = 96.000000,
            scale = 8,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 19",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 25,
            heat_point = 6.000000,
            humidity_point = 45.000000,
            scale = 5,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 20",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 114,
            heat_point = 57.000000,
            humidity_point = 54.000000,
            scale = 1,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 21",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -143,
            heat_point = 23.000000,
            humidity_point = 27.000000,
            scale = 7,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 22",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 86,
            heat_point = 17.000000,
            humidity_point = 20.000000,
            scale = 2,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 23",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -128,
            heat_point = 12.000000,
            humidity_point = 59.000000,
            scale = 10,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 24",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -162,
            heat_point = 47.000000,
            humidity_point = 25.000000,
            scale = 3,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 25",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 74,
            heat_point = 97.000000,
            humidity_point = 94.000000,
            scale = 9,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 26",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 71,
            heat_point = 40.000000,
            humidity_point = 31.000000,
            scale = 5,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 27",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -173,
            heat_point = 84.000000,
            humidity_point = 98.000000,
            scale = 6,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 28",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -5,
            heat_point = 79.000000,
            humidity_point = 85.000000,
            scale = 9,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 29",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -168,
            heat_point = 11.000000,
            humidity_point = 97.000000,
            scale = 6,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 30",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -120,
            heat_point = 67.000000,
            humidity_point = 66.000000,
            scale = 4,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 31",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 8,
            heat_point = 74.000000,
            humidity_point = 93.000000,
            scale = 3,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 32",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 137,
            heat_point = 77.000000,
            humidity_point = 80.000000,
            scale = 1,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 33",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -199,
            heat_point = 31.000000,
            humidity_point = 59.000000,
            scale = 7,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 34",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 123,
            heat_point = 3.000000,
            humidity_point = 54.000000,
            scale = 6,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 35",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 126,
            heat_point = 40.000000,
            humidity_point = 75.000000,
            scale = 8,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 36",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -90,
            heat_point = 85.000000,
            humidity_point = 93.000000,
            scale = 3,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 37",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -36,
            heat_point = 81.000000,
            humidity_point = 43.000000,
            scale = 6,
            offset = 10,
    })
minetest.register_biome({
            name = "Biome No. 38",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -91,
            heat_point = 55.000000,
            humidity_point = 18.000000,
            scale = 10,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 39",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 100,
            heat_point = 40.000000,
            humidity_point = 7.000000,
            scale = 8,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 40",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -22,
            heat_point = 60.000000,
            humidity_point = 78.000000,
            scale = 1,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 41",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -81,
            heat_point = 96.000000,
            humidity_point = 53.000000,
            scale = 9,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 42",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -66,
            heat_point = 26.000000,
            humidity_point = 89.000000,
            scale = 7,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 43",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 65,
            heat_point = 58.000000,
            humidity_point = 59.000000,
            scale = 3,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 44",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 137,
            heat_point = 5.000000,
            humidity_point = 92.000000,
            scale = 5,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 45",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 126,
            heat_point = 24.000000,
            humidity_point = 3.000000,
            scale = 7,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 46",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -131,
            heat_point = 10.000000,
            humidity_point = 95.000000,
            scale = 1,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 47",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -5,
            heat_point = 79.000000,
            humidity_point = 83.000000,
            scale = 2,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 48",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 30,
            heat_point = 25.000000,
            humidity_point = 31.000000,
            scale = 9,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 49",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 82,
            heat_point = 38.000000,
            humidity_point = 27.000000,
            scale = 3,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 50",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 93,
            heat_point = 24.000000,
            humidity_point = 92.000000,
            scale = 4,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 51",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -151,
            heat_point = 8.000000,
            humidity_point = 61.000000,
            scale = 9,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 52",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -199,
            heat_point = 25.000000,
            humidity_point = 32.000000,
            scale = 3,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 53",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -68,
            heat_point = 71.000000,
            humidity_point = 33.000000,
            scale = 4,
            offset = 10,
    })
minetest.register_biome({
            name = "Biome No. 54",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 28,
            heat_point = 8.000000,
            humidity_point = 85.000000,
            scale = 1,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 55",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -43,
            heat_point = 86.000000,
            humidity_point = 90.000000,
            scale = 6,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 56",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -162,
            heat_point = 77.000000,
            humidity_point = 93.000000,
            scale = 2,
            offset = 10,
    })
minetest.register_biome({
            name = "Biome No. 57",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 123,
            heat_point = 55.000000,
            humidity_point = 55.000000,
            scale = 3,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 58",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -197,
            heat_point = 32.000000,
            humidity_point = 26.000000,
            scale = 2,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 59",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -121,
            heat_point = 51.000000,
            humidity_point = 4.000000,
            scale = 5,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 60",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 53,
            heat_point = 27.000000,
            humidity_point = 64.000000,
            scale = 8,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 61",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -5,
            heat_point = 25.000000,
            humidity_point = 48.000000,
            scale = 7,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 62",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -11,
            heat_point = 64.000000,
            humidity_point = 39.000000,
            scale = 8,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 63",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -17,
            heat_point = 60.000000,
            humidity_point = 83.000000,
            scale = 9,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 64",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 40,
            heat_point = 5.000000,
            humidity_point = 7.000000,
            scale = 8,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 65",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -155,
            heat_point = 60.000000,
            humidity_point = 94.000000,
            scale = 4,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 66",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -110,
            heat_point = 43.000000,
            humidity_point = 60.000000,
            scale = 1,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 67",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 108,
            heat_point = 69.000000,
            humidity_point = 94.000000,
            scale = 2,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 68",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -194,
            heat_point = 37.000000,
            humidity_point = 76.000000,
            scale = 0,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 69",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 161,
            heat_point = 18.000000,
            humidity_point = 19.000000,
            scale = 7,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 70",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -6,
            heat_point = 12.000000,
            humidity_point = 28.000000,
            scale = 1,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 71",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 26,
            heat_point = 13.000000,
            humidity_point = 4.000000,
            scale = 9,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 72",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 184,
            heat_point = 97.000000,
            humidity_point = 15.000000,
            scale = 1,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 73",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -58,
            heat_point = 66.000000,
            humidity_point = 22.000000,
            scale = 3,
            offset = 0,
    })
minetest.register_biome({
            name = "Biome No. 74",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 163,
            heat_point = 94.000000,
            humidity_point = 26.000000,
            scale = 5,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 75",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -128,
            heat_point = 80.000000,
            humidity_point = 91.000000,
            scale = 8,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 76",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -124,
            heat_point = 76.000000,
            humidity_point = 97.000000,
            scale = 7,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 77",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 186,
            heat_point = 66.000000,
            humidity_point = 40.000000,
            scale = 4,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 78",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 121,
            heat_point = 66.000000,
            humidity_point = 98.000000,
            scale = 1,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 79",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 81,
            heat_point = 7.000000,
            humidity_point = 62.000000,
            scale = 9,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 80",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -171,
            heat_point = 56.000000,
            humidity_point = 34.000000,
            scale = 1,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 81",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -39,
            heat_point = 80.000000,
            humidity_point = 60.000000,
            scale = 10,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 82",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -26,
            heat_point = 2.000000,
            humidity_point = 64.000000,
            scale = 9,
            offset = 10,
    })
minetest.register_biome({
            name = "Biome No. 83",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -66,
            heat_point = 79.000000,
            humidity_point = 35.000000,
            scale = 0,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 84",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -126,
            heat_point = 75.000000,
            humidity_point = 21.000000,
            scale = 9,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 85",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 84,
            heat_point = 95.000000,
            humidity_point = 66.000000,
            scale = 4,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 86",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 137,
            heat_point = 59.000000,
            humidity_point = 98.000000,
            scale = 9,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 87",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 138,
            heat_point = 19.000000,
            humidity_point = 88.000000,
            scale = 3,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 88",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -17,
            heat_point = 58.000000,
            humidity_point = 44.000000,
            scale = 1,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 89",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -126,
            heat_point = 13.000000,
            humidity_point = 55.000000,
            scale = 0,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 90",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -11,
            heat_point = 53.000000,
            humidity_point = 26.000000,
            scale = 4,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 91",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 19,
            heat_point = 31.000000,
            humidity_point = 62.000000,
            scale = 5,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 92",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -157,
            heat_point = 70.000000,
            humidity_point = 23.000000,
            scale = 5,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 93",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 182,
            heat_point = 48.000000,
            humidity_point = 27.000000,
            scale = 2,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 94",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 75,
            heat_point = 28.000000,
            humidity_point = 73.000000,
            scale = 1,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 95",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 15,
            heat_point = 18.000000,
            humidity_point = 80.000000,
            scale = 5,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 96",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -184,
            heat_point = 97.000000,
            humidity_point = 66.000000,
            scale = 5,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 97",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 61,
            heat_point = 95.000000,
            humidity_point = 95.000000,
            scale = 8,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 98",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 8,
            heat_point = 84.000000,
            humidity_point = 76.000000,
            scale = 2,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 99",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -37,
            heat_point = 95.000000,
            humidity_point = 86.000000,
            scale = 2,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 100",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 139,
            heat_point = 76.000000,
            humidity_point = 84.000000,
            scale = 3,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 101",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -93,
            heat_point = 13.000000,
            humidity_point = 69.000000,
            scale = 5,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 102",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -191,
            heat_point = 46.000000,
            humidity_point = 2.000000,
            scale = 7,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 103",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -61,
            heat_point = 98.000000,
            humidity_point = 74.000000,
            scale = 7,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 104",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 47,
            heat_point = 24.000000,
            humidity_point = 14.000000,
            scale = 3,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 105",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 157,
            heat_point = 19.000000,
            humidity_point = 42.000000,
            scale = 0,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 106",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 195,
            heat_point = 96.000000,
            humidity_point = 85.000000,
            scale = 3,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 107",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 198,
            heat_point = 45.000000,
            humidity_point = 47.000000,
            scale = 3,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 108",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -198,
            heat_point = 14.000000,
            humidity_point = 87.000000,
            scale = 3,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 109",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 111,
            heat_point = 42.000000,
            humidity_point = 42.000000,
            scale = 10,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 110",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 42,
            heat_point = 1.000000,
            humidity_point = 64.000000,
            scale = 8,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 111",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 131,
            heat_point = 38.000000,
            humidity_point = 83.000000,
            scale = 2,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 112",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -190,
            heat_point = 69.000000,
            humidity_point = 57.000000,
            scale = 4,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 113",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -30,
            heat_point = 31.000000,
            humidity_point = 48.000000,
            scale = 1,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 114",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -78,
            heat_point = 16.000000,
            humidity_point = 43.000000,
            scale = 6,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 115",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 85,
            heat_point = 76.000000,
            humidity_point = 15.000000,
            scale = 4,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 116",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -131,
            heat_point = 66.000000,
            humidity_point = 3.000000,
            scale = 8,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 117",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -49,
            heat_point = 23.000000,
            humidity_point = 43.000000,
            scale = 3,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 118",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -68,
            heat_point = 14.000000,
            humidity_point = 44.000000,
            scale = 3,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 119",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -78,
            heat_point = 62.000000,
            humidity_point = 90.000000,
            scale = 9,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 120",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 168,
            heat_point = 48.000000,
            humidity_point = 53.000000,
            scale = 4,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 121",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 40,
            heat_point = 78.000000,
            humidity_point = 13.000000,
            scale = 7,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 122",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 120,
            heat_point = 52.000000,
            humidity_point = 55.000000,
            scale = 6,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 123",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 193,
            heat_point = 17.000000,
            humidity_point = 17.000000,
            scale = 7,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 124",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -53,
            heat_point = 64.000000,
            humidity_point = 73.000000,
            scale = 3,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 125",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -14,
            heat_point = 71.000000,
            humidity_point = 75.000000,
            scale = 8,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 126",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -100,
            heat_point = 47.000000,
            humidity_point = 73.000000,
            scale = 3,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 127",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -117,
            heat_point = 79.000000,
            humidity_point = 14.000000,
            scale = 3,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 128",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 134,
            heat_point = 74.000000,
            humidity_point = 29.000000,
            scale = 6,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 129",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -132,
            heat_point = 12.000000,
            humidity_point = 92.000000,
            scale = 8,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 130",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 190,
            heat_point = 40.000000,
            humidity_point = 47.000000,
            scale = 9,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 131",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -13,
            heat_point = 28.000000,
            humidity_point = 76.000000,
            scale = 6,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 132",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 136,
            heat_point = 42.000000,
            humidity_point = 67.000000,
            scale = 6,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 133",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -45,
            heat_point = 49.000000,
            humidity_point = 96.000000,
            scale = 0,
            offset = 0,
    })
minetest.register_biome({
            name = "Biome No. 134",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -16,
            heat_point = 40.000000,
            humidity_point = 47.000000,
            scale = 5,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 135",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 52,
            heat_point = 50.000000,
            humidity_point = 47.000000,
            scale = 6,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 136",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 144,
            heat_point = 64.000000,
            humidity_point = 60.000000,
            scale = 6,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 137",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 152,
            heat_point = 64.000000,
            humidity_point = 73.000000,
            scale = 5,
            offset = 10,
    })
minetest.register_biome({
            name = "Biome No. 138",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -7,
            heat_point = 1.000000,
            humidity_point = 64.000000,
            scale = 8,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 139",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 88,
            heat_point = 5.000000,
            humidity_point = 52.000000,
            scale = 9,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 140",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 62,
            heat_point = 52.000000,
            humidity_point = 47.000000,
            scale = 7,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 141",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 125,
            heat_point = 91.000000,
            humidity_point = 82.000000,
            scale = 6,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 142",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 168,
            heat_point = 60.000000,
            humidity_point = 13.000000,
            scale = 1,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 143",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 144,
            heat_point = 37.000000,
            humidity_point = 39.000000,
            scale = 6,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 144",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 137,
            heat_point = 92.000000,
            humidity_point = 79.000000,
            scale = 4,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 145",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 38,
            heat_point = 39.000000,
            humidity_point = 6.000000,
            scale = 1,
            offset = 10,
    })
minetest.register_biome({
            name = "Biome No. 146",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 31,
            heat_point = 37.000000,
            humidity_point = 64.000000,
            scale = 4,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 147",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -23,
            heat_point = 71.000000,
            humidity_point = 69.000000,
            scale = 3,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 148",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 27,
            heat_point = 55.000000,
            humidity_point = 75.000000,
            scale = 1,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 149",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -8,
            heat_point = 27.000000,
            humidity_point = 74.000000,
            scale = 9,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 150",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -189,
            heat_point = 20.000000,
            humidity_point = 7.000000,
            scale = 6,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 151",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -53,
            heat_point = 36.000000,
            humidity_point = 87.000000,
            scale = 9,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 152",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -94,
            heat_point = 88.000000,
            humidity_point = 96.000000,
            scale = 6,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 153",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 161,
            heat_point = 76.000000,
            humidity_point = 84.000000,
            scale = 9,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 154",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -149,
            heat_point = 88.000000,
            humidity_point = 74.000000,
            scale = 3,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 155",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -113,
            heat_point = 50.000000,
            humidity_point = 59.000000,
            scale = 3,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 156",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -181,
            heat_point = 70.000000,
            humidity_point = 18.000000,
            scale = 4,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 157",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -106,
            heat_point = 11.000000,
            humidity_point = 56.000000,
            scale = 5,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 158",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -33,
            heat_point = 84.000000,
            humidity_point = 42.000000,
            scale = 7,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 159",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -124,
            heat_point = 76.000000,
            humidity_point = 67.000000,
            scale = 3,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 160",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 34,
            heat_point = 35.000000,
            humidity_point = 69.000000,
            scale = 1,
            offset = 10,
    })
minetest.register_biome({
            name = "Biome No. 161",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 144,
            heat_point = 70.000000,
            humidity_point = 17.000000,
            scale = 3,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 162",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -107,
            heat_point = 65.000000,
            humidity_point = 65.000000,
            scale = 4,
            offset = 0,
    })
minetest.register_biome({
            name = "Biome No. 163",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 194,
            heat_point = 82.000000,
            humidity_point = 97.000000,
            scale = 5,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 164",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 5,
            heat_point = 8.000000,
            humidity_point = 18.000000,
            scale = 4,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 165",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 182,
            heat_point = 12.000000,
            humidity_point = 44.000000,
            scale = 9,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 166",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 29,
            heat_point = 85.000000,
            humidity_point = 98.000000,
            scale = 3,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 167",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -44,
            heat_point = 81.000000,
            humidity_point = 69.000000,
            scale = 10,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 168",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -54,
            heat_point = 21.000000,
            humidity_point = 57.000000,
            scale = 1,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 169",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 126,
            heat_point = 72.000000,
            humidity_point = 6.000000,
            scale = 2,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 170",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 145,
            heat_point = 41.000000,
            humidity_point = 63.000000,
            scale = 6,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 171",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -1,
            heat_point = 24.000000,
            humidity_point = 90.000000,
            scale = 2,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 172",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 192,
            heat_point = 78.000000,
            humidity_point = 68.000000,
            scale = 2,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 173",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 156,
            heat_point = 10.000000,
            humidity_point = 60.000000,
            scale = 2,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 174",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -158,
            heat_point = 72.000000,
            humidity_point = 94.000000,
            scale = 5,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 175",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -37,
            heat_point = 5.000000,
            humidity_point = 64.000000,
            scale = 7,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 176",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 138,
            heat_point = 50.000000,
            humidity_point = 78.000000,
            scale = 4,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 177",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -14,
            heat_point = 25.000000,
            humidity_point = 48.000000,
            scale = 6,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 178",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 114,
            heat_point = 17.000000,
            humidity_point = 87.000000,
            scale = 1,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 179",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 60,
            heat_point = 89.000000,
            humidity_point = 71.000000,
            scale = 4,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 180",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 64,
            heat_point = 56.000000,
            humidity_point = 2.000000,
            scale = 2,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 181",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 65,
            heat_point = 29.000000,
            humidity_point = 76.000000,
            scale = 9,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 182",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -92,
            heat_point = 83.000000,
            humidity_point = 5.000000,
            scale = 5,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 183",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 110,
            heat_point = 43.000000,
            humidity_point = 17.000000,
            scale = 5,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 184",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 12,
            heat_point = 39.000000,
            humidity_point = 46.000000,
            scale = 8,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 185",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -144,
            heat_point = 2.000000,
            humidity_point = 41.000000,
            scale = 1,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 186",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -59,
            heat_point = 77.000000,
            humidity_point = 31.000000,
            scale = 0,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 187",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 77,
            heat_point = 60.000000,
            humidity_point = 10.000000,
            scale = 4,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 188",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 101,
            heat_point = 82.000000,
            humidity_point = 21.000000,
            scale = 1,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 189",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -136,
            heat_point = 18.000000,
            humidity_point = 89.000000,
            scale = 3,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 190",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -82,
            heat_point = 97.000000,
            humidity_point = 70.000000,
            scale = 3,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 191",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 156,
            heat_point = 9.000000,
            humidity_point = 38.000000,
            scale = 9,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 192",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -50,
            heat_point = 87.000000,
            humidity_point = 84.000000,
            scale = 3,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 193",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -38,
            heat_point = 92.000000,
            humidity_point = 64.000000,
            scale = 5,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 194",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 186,
            heat_point = 43.000000,
            humidity_point = 36.000000,
            scale = 3,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 195",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 10,
            heat_point = 8.000000,
            humidity_point = 80.000000,
            scale = 6,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 196",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -70,
            heat_point = 53.000000,
            humidity_point = 13.000000,
            scale = 2,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 197",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -99,
            heat_point = 33.000000,
            humidity_point = 69.000000,
            scale = 2,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 198",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 135,
            heat_point = 22.000000,
            humidity_point = 16.000000,
            scale = 1,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 199",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 167,
            heat_point = 54.000000,
            humidity_point = 54.000000,
            scale = 2,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 200",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 191,
            heat_point = 59.000000,
            humidity_point = 74.000000,
            scale = 9,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 201",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -156,
            heat_point = 68.000000,
            humidity_point = 64.000000,
            scale = 9,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 202",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 170,
            heat_point = 21.000000,
            humidity_point = 1.000000,
            scale = 1,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 203",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -109,
            heat_point = 87.000000,
            humidity_point = 74.000000,
            scale = 9,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 204",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -95,
            heat_point = 69.000000,
            humidity_point = 73.000000,
            scale = 3,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 205",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 20,
            heat_point = 48.000000,
            humidity_point = 80.000000,
            scale = 7,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 206",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -40,
            heat_point = 39.000000,
            humidity_point = 95.000000,
            scale = 5,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 207",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 18,
            heat_point = 70.000000,
            humidity_point = 95.000000,
            scale = 6,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 208",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -153,
            heat_point = 36.000000,
            humidity_point = 45.000000,
            scale = 6,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 209",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -45,
            heat_point = 48.000000,
            humidity_point = 89.000000,
            scale = 8,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 210",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -13,
            heat_point = 18.000000,
            humidity_point = 32.000000,
            scale = 1,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 211",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 134,
            heat_point = 9.000000,
            humidity_point = 22.000000,
            scale = 7,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 212",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 106,
            heat_point = 57.000000,
            humidity_point = 92.000000,
            scale = 9,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 213",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 65,
            heat_point = 81.000000,
            humidity_point = 52.000000,
            scale = 3,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 214",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -83,
            heat_point = 66.000000,
            humidity_point = 28.000000,
            scale = 2,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 215",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 98,
            heat_point = 14.000000,
            humidity_point = 69.000000,
            scale = 2,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 216",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -9,
            heat_point = 56.000000,
            humidity_point = 72.000000,
            scale = 10,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 217",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -114,
            heat_point = 20.000000,
            humidity_point = 63.000000,
            scale = 1,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 218",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -154,
            heat_point = 32.000000,
            humidity_point = 34.000000,
            scale = 9,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 219",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 134,
            heat_point = 34.000000,
            humidity_point = 8.000000,
            scale = 3,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 220",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -178,
            heat_point = 65.000000,
            humidity_point = 48.000000,
            scale = 5,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 221",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -55,
            heat_point = 11.000000,
            humidity_point = 99.000000,
            scale = 4,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 222",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 187,
            heat_point = 48.000000,
            humidity_point = 49.000000,
            scale = 7,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 223",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -8,
            heat_point = 76.000000,
            humidity_point = 3.000000,
            scale = 6,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 224",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -8,
            heat_point = 33.000000,
            humidity_point = 41.000000,
            scale = 3,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 225",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -174,
            heat_point = 98.000000,
            humidity_point = 29.000000,
            scale = 1,
            offset = 5,
    })
minetest.register_biome({
            name = "Biome No. 226",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 134,
            heat_point = 42.000000,
            humidity_point = 69.000000,
            scale = 4,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 227",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -154,
            heat_point = 70.000000,
            humidity_point = 23.000000,
            scale = 6,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 228",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -4,
            heat_point = 26.000000,
            humidity_point = 58.000000,
            scale = 9,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 229",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 94,
            heat_point = 76.000000,
            humidity_point = 37.000000,
            scale = 1,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 230",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 199,
            heat_point = 79.000000,
            humidity_point = 21.000000,
            scale = 5,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 231",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 178,
            heat_point = 12.000000,
            humidity_point = 8.000000,
            scale = 2,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 232",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -163,
            heat_point = 48.000000,
            humidity_point = 84.000000,
            scale = 9,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 233",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -40,
            heat_point = 1.000000,
            humidity_point = 61.000000,
            scale = 8,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 234",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 73,
            heat_point = 56.000000,
            humidity_point = 5.000000,
            scale = 7,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 235",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 78,
            heat_point = 94.000000,
            humidity_point = 19.000000,
            scale = 10,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 236",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 191,
            heat_point = 26.000000,
            humidity_point = 61.000000,
            scale = 1,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 237",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 17,
            heat_point = 86.000000,
            humidity_point = 40.000000,
            scale = 9,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 238",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -155,
            heat_point = 88.000000,
            humidity_point = 73.000000,
            scale = 3,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 239",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 67,
            heat_point = 3.000000,
            humidity_point = 99.000000,
            scale = 7,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 240",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 185,
            heat_point = 93.000000,
            humidity_point = 69.000000,
            scale = 5,
            offset = 3,
    })
minetest.register_biome({
            name = "Biome No. 241",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -61,
            heat_point = 64.000000,
            humidity_point = 83.000000,
            scale = 1,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 242",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 24,
            heat_point = 48.000000,
            humidity_point = 66.000000,
            scale = 6,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 243",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -12,
            heat_point = 100.000000,
            humidity_point = 5.000000,
            scale = 3,
            offset = 0,
    })
minetest.register_biome({
            name = "Biome No. 244",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -35,
            heat_point = 67.000000,
            humidity_point = 14.000000,
            scale = 8,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 245",
            top_node = "default:gravel",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -114,
            heat_point = 6.000000,
            humidity_point = 55.000000,
            scale = 6,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 246",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -128,
            heat_point = 23.000000,
            humidity_point = 100.000000,
            scale = 4,
            offset = 8,
    })
minetest.register_biome({
            name = "Biome No. 247",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 191,
            heat_point = 61.000000,
            humidity_point = 88.000000,
            scale = 7,
            offset = 6,
    })
minetest.register_biome({
            name = "Biome No. 248",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -140,
            heat_point = 65.000000,
            humidity_point = 70.000000,
            scale = 3,
            offset = 4,
    })
minetest.register_biome({
            name = "Biome No. 249",
            top_node = "default:sand",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 137,
            heat_point = 64.000000,
            humidity_point = 91.000000,
            scale = 9,
            offset = 0,
    })
minetest.register_biome({
            name = "Biome No. 250",
            top_node = "default:dirt",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 102,
            heat_point = 5.000000,
            humidity_point = 85.000000,
            scale = 9,
            offset = 2,
    })
minetest.register_biome({
            name = "Biome No. 251",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 194,
            heat_point = 7.000000,
            humidity_point = 47.000000,
            scale = 2,
            offset = 9,
    })
minetest.register_biome({
            name = "Biome No. 252",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -62,
            heat_point = 53.000000,
            humidity_point = 8.000000,
            scale = 9,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 253",
            top_node = "default:dirt_with_grass",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = 165,
            heat_point = 89.000000,
            humidity_point = 98.000000,
            scale = 2,
            offset = 1,
    })
minetest.register_biome({
            name = "Biome No. 254",
            top_node = "default:sandstone",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -118,
            heat_point = 30.000000,
            humidity_point = 18.000000,
            scale = 4,
            offset = 7,
    })
minetest.register_biome({
            name = "Biome No. 255",
            top_node = "default:cobble",
            filler_node = "default:stone",
            top_depth = 4,
            height_point = -93,
            heat_point = 37.000000,
            humidity_point = 6.000000,
            scale = 10,
            offset = 5,
    })